services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: crop_recommendation_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROOT
    ports:
      - "5432:5432"
   

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy