services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: crop_recommendation_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROOT
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy