services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crop_recommendation_system'
      - 'POSTGRES_PASSWORD=ROOT'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
