spring.application.name=backend
server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=postgresql://mypostgres:mPoD4j0L0Shwa9M5JTAhsdgk0jJLEX9O@dpg-d7ndmttckfvc73eu55eg-a/mydb_u1i4
spring.datasource.username=mypostgres
spring.datasource.password=mPoD4j0L0Shwa9M5JTAhsdgk0jJLEX9O
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.app.jwtSecret=mySuperLongJwtSecretKeyThatIsAtLeastThirtyTwoChars123!
spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=cropRecommendationSystemCookie

#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshilkothiya2005@gmail.com
spring.mail.password=vxvj ompk vfno ulme
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

frontend.url=http://localhost:5173