spring.application.name=backend
server.port=${PORT:8080}

# Database (Render will provide values)
spring.datasource.url=jdbc:postgresql://localhost:5432/crop_recommendation_system
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT
spring.app.jwtSecret=${JWT_SECRET:mySuperLongJwtSecretKeyThatIsAtLeastThirtyTwoChars123!}

spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=cropRecommendationSystemCookie

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshilkothiya2005@gmail.com
spring.mail.password=vxvj ompk vfno ulme
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# Frontend (update after deploy)
frontend.url=${FRONTEND_URL:http://localhost:5173}