spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/crop_recommendation_system
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.housekeeping-period-ms=300000
spring.datasource.hikari.maximum-pool-size=10


spring.app.jwtSecret=mySuperLongJwtSecretKeyThatIsAtLeastThirtyTwoChars123!
spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=cropRecommendationSystemCookie

frontend.url=http://localhost:5173/
